stages:
- name: Build
  steps:
  - runScriptConfig:
      image: gcc:latest
      shellScript: go build -o HelloApp ./main.go
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34407
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
