stages:
- name: Build
  steps:
  - runScriptConfig:
      image: golang:1.13.3
      shellScript: |-
        mkdir -p /go/src/github.com/erickmaria
        ln -s `pwd` /go/src/github.com/erickmaria/helloapp
        cd /go/src/github.com/erickmaria/helloapp
        go build -o bin/helloapp
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}:v${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34407
- name: Deploy
  steps:
  - runScriptConfig:
      image: emrds/rancher-kubectl:v2.2.0
      shellScript: |-
        rancher login https://35.196.211.203/ --token token-9fpvl:mhv56mf77685dvczz668jm98znrb8rj28rz9kb28wsvpdvpg6wzzcq --skip-verify
        rancher kubectl create namespace ${CICD_GIT_REPO_NAME}-v${CICD_EXECUTION_SEQUENCE}
        apk add curl
        curl -O https://raw.githubusercontent.com/ErickMaria/helloapp/master/deployment.yaml
        cat deployment.yaml | kubectl apply -f
timeout: 60
notification: {}
