stages:
- name: Build
  steps:
  - runScriptConfig:
      image: golang:1.13.3
      shellScript: |-
        mkdir -p /go/src/github.com/erickmaria
        ln -s `pwd` /go/src/github.com/erickmaria/helloapp
        cd /go/src/github.com/erickmaria/helloapp
        go build -o bin/helloapp
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}:v${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34407
- name: Deploy
  steps:
  - runScriptConfig:
      image: golang:latest
      shellScript: |-
        curl -k -s -X POST \
          https://23.100.28.108/v3/clusters/c-7f9bf/namespaces \
          -H 'Authorization: Bearer ${API_TOKEN}' \
          -H 'Content-Type: application/json' \
          -d '{"containerDefaultResourceLimit":null, "name":"'${CICD_GIT_REPO_NAME}-v${CICD_EXECUTION_SEQUENCE}'", "projectId":"c-7f9bf:p-sr6dq", "resourceQuota":null}'
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
