stages:
- name: Build
  steps:
  - runScriptConfig:
      image: golang:1.13.3
      shellScript: |-
        mkdir -p /go/src/github.com/erickmaria
        ln -s `pwd` /go/src/github.com/erickmaria/helloapp
        cd /go/src/github.com/erickmaria/helloapp
        go build -o bin/helloapp
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}:v${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34407
- name: Deploy
  steps:
  - runScriptConfig:
      image: golang:latest
      shellScript: |
        curl -k -u "token-hwrzz:gtv62pdcbdzmf9zw576q4l8wjtqhg5ng57rmckpfmdw6sdw5msz6xw" \
        -X POST \
        -H 'Accept: application/json' \
        -H 'Content-Type: application/json' \
        -d '{"containerDefaultResourceLimit":null, "name":"'${CICD_EXECUTION_SEQUENCE}'", "projectId":"c-mvdt8:p-s5xh6", "resourceQuota":null}' \
        'https://35.196.211.203/v3/cluster/c-7f9bf/namespaces'
  - runScriptConfig:
      image: emrds/rancher-kubectl
      shellScript: |-
        rancher login https://35.196.211.203/ --token token-hwrzz:gtv62pdcbdzmf9zw576q4l8wjtqhg5ng57rmckpfmdw6sdw5msz6xw --skip-veri
        fy
        rancher kubectl -f https://raw.githubusercontent.com/ErickMaria/helloapp/master/deployment.yaml
timeout: 60
notification: {}
