stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: helloapp:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 127.0.0.1:34430
notification: {}
