stages:
- name: Build
  steps:
  - runScriptConfig:
      image: golang:1.12.7-alpine
      shellScript: go build -o Helloapp ldflags '-libgcc=none' .
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: testcr/helloapp:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
