kind: Service
apiVersion: v1
metadata:
  name: ${CICD_GIT_REPO_NAME}-v${CICD_EXECUTION_SEQUENCE}
  namespace: application
spec:
  selector:
    app: ${CICD_GIT_REPO_NAME}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${CICD_GIT_REPO_NAME}-v${CICD_EXECUTION_SEQUENCE}
  namespace: application
  labels:
    app: ${CICD_GIT_REPO_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${CICD_GIT_REPO_NAME}
  template:
    metadata:
      labels:
        app: ${CICD_GIT_REPO_NAME}
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: ${CICD_GIT_REPO_NAME}
        image: ${CICD_IMAGE}:v${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8081
